### ISSUE TITLE
Clashing convention metadata

### ISSUE THREAD

**Issue by hot007** [ACDguide/Governance#83] opened 2023-10-26 00:31 UTC
Should add a note on [conventions page](https://acdguide.github.io/Governance/concepts/other-conventions.html?highlight=ugrid) that when adhering to two different metadata standards their requirements can clash, e.g.

> Annoyingly, the [CF] checker picks up on "mesh_topology" and "face_node_connectivity" which are UGRID-1.0 conventions for cf_role, but do not exist in the CF standard (latest CF is 1.10: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html). I'm [not] sure they're going to support UGRID any time soon, so we may just have to wear it in this case.

H/t @janomecopter

**Comment by paolap** [comment] 2024-05-28 23:25
To clarify for myself , the issue is that cf_role is used differently in the two conventions and that the only 3 allowed values in cf v 10 exclude the ones required by UGRID.
Oddly enough this is nearly touched in this CF issue about potentially deprecating cf_role:

https://github.com/cf-convention/cf-conventions/issues/430

However, they don't mention or point out the clash, they do mention that UGRID will be integrated in CF v 11:  
"A few notes on the UGRID, which will be in CF-1.11. As far as I know, the only mandatory use of cf_role in UGRID is for identification of the mesh topology variable"

Couldn't find much about this except for this other ticket:
https://github.com/cf-convention/cf-conventions/issues/357

however, cf_role isn't explicitly mentioned

**Comment by paolap** [comment] 2024-05-28 23:47
Actually I found a more relevant issue which covers cf_role and the integration of UGRID in CF:
https://github.com/cf-convention/cf-conventions/issues/501

**Comment by hot007** [comment] 2024-05-29 02:48
Awesome, good find thanks @paolap !

**Closed** 2024-06-05 07:08 UTC
